# Generated by Django 5.0.4 on 2024-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subaccount_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
