# Generated by Django 5.0.4 on 2024-05-06 20:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_userresponse_accepted_userresponse_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
