# Generated by Django 5.0.4 on 2024-05-08 12:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_announcement_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
