# Generated by Django 5.0.4 on 2024-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_userresponse_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(default='/', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='file',
            field=models.FileField(default='/', upload_to='media/'),
        ),
    ]
