# Generated by Django 5.0.4 on 2024-05-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_announcement_file_userresponse_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='file',
        ),
        migrations.CreateModel(
            name='AnnouncementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='/', upload_to='media/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='/', upload_to='media/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.userresponse')),
            ],
        ),
    ]
